### ISSUE TITLE
URGENT - short redirects not working

### ISSUE THREAD

**Issue by amilkh** [gevuong/minimal-i18n-with-app-router#112]
cannot release unless fixed

- [x] rename press release page to News 
- [x] add 11 news articles from https://virufy.org/news to News page
- [x] create redirect to news page from https://virufy.org/press
- [x] add page https://virufy.org/virumap-msg
- [x] add page https://virufy.org/virumap-slides

**Comment by a-wong-8** [comment]
figma for news page is needed

**Comment by amilkh** [comment]
use the same as our current website !

**Comment by gevuong** [comment]
> * [ ]  add page https://virufy.org/virumap-msg
> * [ ]  add page https://virufy.org/virumap-slides

`/virumap-msg` and `/virumap-slides` were added a few months ago when it was added to 4.0:
https://gevuong.github.io/minimal-i18n-with-app-router/en/virumap-msg
https://gevuong.github.io/minimal-i18n-with-app-router/en/virumap-slides

The current domain `gevuong.github.io/minimal-i18n-with-app-router` is expected to change to `virufy.org` upon release of 6.0. The Japanese equivalent requires changing `/en` to `/ja` in the url.

> * [ ]  add page https://virufy.org/news
> * [ ]  add page https://virufy.org/press

They both link to `/news`. In order to proceed with development in an efficient manner,  these are the recommended steps in order of highest priority:
- [ ] Create a Figma design for the page to match design system.
- [ ] Get design reviewed and approved (by Deepika and/or Gabriela).
- [ ] Have Japan team translate the page.
- [ ] Implement `/news` page, including Japanese translations.

**Comment by amilkh** [comment]
Thank you! Please match the current Web page for now. Rather than tagging
me on pr's, it's better work directly with Kajol.
A bit low on bandwidth 😢
